services:
  api:
    environment:
      - DJANGO_SETTINGS_MODULE=CoreRoot.settings.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app 
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000" 


  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
